# Generated by Django 6.1 on 2026-08-29 20:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img_ruta/')),
                ('categoria', models.CharField(choices=[('Eje transversal', 'eje transversal'), ('Agroproductivo', 'agroproductivo'), ('Tecnico industrial', 'tecnico industrial'), ('Creativo digital', 'creativo digital')], default='Eje transversal', max_length=200)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('puntuacion', models.IntegerField(help_text='Califica del 1 al 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('nivel', models.CharField(choices=[('Modulo Base', 'modulo base'), ('Nivel III', 'nivel III'), ('Nivel II', 'nivel II'), ('Nivel I', 'nivel I')], default='Modulo base', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Seccion_petrolera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Card_petrolera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('nivel', models.CharField(choices=[('Modulo Base', 'modulo base'), ('Nivel III', 'nivel III'), ('Nivel II', 'nivel II'), ('Nivel I', 'nivel I')], default='Modulo base', max_length=200)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.seccion_petrolera')),
            ],
        ),
    ]
