# Generated by Django 6.1 on 2026-08-30 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['orden', 'titulo'], 'verbose_name': 'Beneficio diferencial', 'verbose_name_plural': 'Beneficios diferenciales'},
        ),
        migrations.AlterModelOptions(
            name='card_petrolera',
            options={'ordering': ['orden', 'titulo'], 'verbose_name': 'Programa petrolero', 'verbose_name_plural': 'Programas petroleros'},
        ),
        migrations.AlterModelOptions(
            name='ruta',
            options={'ordering': ['-destacada', 'titulo'], 'verbose_name': 'Ruta', 'verbose_name_plural': 'Rutas'},
        ),
        migrations.AlterModelOptions(
            name='seccion_petrolera',
            options={'ordering': ['orden', 'titulo'], 'verbose_name': 'Sección petrolera', 'verbose_name_plural': 'Secciones petroleras'},
        ),
        migrations.AddField(
            model_name='card',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card_petrolera',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ruta',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='descripcion_corta',
            field=models.CharField(blank=True, help_text='Resumen para cards', max_length=300),
        ),
        migrations.AddField(
            model_name='ruta',
            name='destacada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ruta',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='seccion_petrolera',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='card_petrolera',
            name='nivel',
            field=models.CharField(choices=[('Modulo Base', 'Módulo Base'), ('Nivel III', 'Nivel III'), ('Nivel II', 'Nivel II'), ('Nivel I', 'Nivel I')], default='Modulo Base', max_length=50),
        ),
        migrations.AlterField(
            model_name='card_petrolera',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='main.seccion_petrolera'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='categoria',
            field=models.CharField(choices=[('Eje transversal', 'Eje transversal'), ('Agroproductivo', 'Agroproductivo'), ('Tecnico industrial', 'Técnico industrial'), ('Creativo digital', 'Creativo digital')], db_index=True, default='Eje transversal', max_length=50),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img_ruta/'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='nivel',
            field=models.CharField(choices=[('Modulo Base', 'Módulo Base'), ('Nivel III', 'Nivel III'), ('Nivel II', 'Nivel II'), ('Nivel I', 'Nivel I')], db_index=True, default='Modulo Base', max_length=50),
        ),
    ]
