# Generated by Django 6.1 on 2026-08-30 21:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_card_options_alter_card_petrolera_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_petrolera',
            name='competencias',
            field=models.TextField(blank=True, help_text='Una por línea'),
        ),
        migrations.AddField(
            model_name='card_petrolera',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción larga del programa'),
        ),
        migrations.AddField(
            model_name='card_petrolera',
            name='descripcion_corta',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='card_petrolera',
            name='duracion_horas',
            field=models.PositiveIntegerField(default=180),
        ),
        migrations.AddField(
            model_name='card_petrolera',
            name='duracion_semanas',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='card_petrolera',
            name='incluye',
            field=models.TextField(blank=True, default='Open Badges 3.0 · Práctica en campo · Analítica con IA'),
        ),
        migrations.AddField(
            model_name='card_petrolera',
            name='instructor',
            field=models.CharField(blank=True, default='Equipo Formación Petrolera', max_length=200),
        ),
        migrations.AddField(
            model_name='card_petrolera',
            name='modalidad',
            field=models.CharField(default='Semipresencial AI-First', max_length=100),
        ),
        migrations.AddField(
            model_name='card_petrolera',
            name='objetivos',
            field=models.TextField(blank=True, help_text='Un objetivo por línea'),
        ),
        migrations.AddField(
            model_name='card_petrolera',
            name='puntuacion',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='card_petrolera',
            name='requisitos',
            field=models.TextField(blank=True, help_text='Uno por línea'),
        ),
        migrations.AddField(
            model_name='card_petrolera',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='card_petrolera',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos_petrolera/'),
        ),
        migrations.AddField(
            model_name='card_petrolera',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube/Vimeo URL'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='competencias',
            field=models.TextField(blank=True, help_text='Competencias, una por línea'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='cupos',
            field=models.PositiveIntegerField(blank=True, default=30),
        ),
        migrations.AddField(
            model_name='ruta',
            name='duracion_horas',
            field=models.PositiveIntegerField(default=180, help_text='Duración total en horas'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='duracion_semanas',
            field=models.PositiveIntegerField(default=6, help_text='Semanas'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='incluye',
            field=models.TextField(blank=True, default='Open Badges 3.0 · Tutor IA · Proyecto integrador', help_text='Qué incluye, separado por · o líneas'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='instructor',
            field=models.CharField(blank=True, default='Equipo CVMTE', max_length=200),
        ),
        migrations.AddField(
            model_name='ruta',
            name='modalidad',
            field=models.CharField(default='Semipresencial AI-First', max_length=100),
        ),
        migrations.AddField(
            model_name='ruta',
            name='objetivos',
            field=models.TextField(blank=True, help_text='Un objetivo por línea'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='requisitos',
            field=models.TextField(blank=True, help_text='Requisitos, uno por línea'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='video_file',
            field=models.FileField(blank=True, help_text='O sube un MP4 local', null=True, upload_to='videos_ruta/'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube/Vimeo URL (ej: https://www.youtube.com/watch?v=...)'),
        ),
    ]
