# Generated by Django 6.1 on 2026-08-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_card_petrolera_competencias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_petrolera',
            name='img',
            field=models.ImageField(blank=True, help_text='Imagen representativa del programa', null=True, upload_to='img_petrolera/'),
        ),
    ]
