# Generated by Django 6.1 on 2026-08-30 21:57

import django.core.validators
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_card_petrolera_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card_petrolera',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='video_url',
        ),
        migrations.AlterField(
            model_name='card_petrolera',
            name='video_file',
            field=models.FileField(blank=True, help_text='Video del programa (MP4/WebM/MOV, máx 500 MB). Subido por administrador.', null=True, upload_to='videos_petrolera/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov', 'mkv']), main.models.validate_video_size]),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='video_file',
            field=models.FileField(blank=True, help_text='Video del curso (MP4/WebM/MOV, máx 500 MB). Subido por administrador.', null=True, upload_to='videos_ruta/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov', 'mkv']), main.models.validate_video_size]),
        ),
    ]
