# Generated by Django 6.1 on 2026-08-30 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_card_petrolera_video_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('en_progreso', 'En progreso'), ('completado', 'Completado')], default='en_progreso', max_length=20)),
                ('completado', models.BooleanField(default=False)),
                ('iniciado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('completado_en', models.DateTimeField(blank=True, null=True)),
                ('programa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='main.card_petrolera')),
                ('ruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='main.ruta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progreso',
                'verbose_name_plural': 'Progresos',
                'ordering': ['-actualizado_en'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ruta__isnull', False)), fields=('usuario', 'ruta'), name='uniq_usuario_ruta'), models.UniqueConstraint(condition=models.Q(('programa__isnull', False)), fields=('usuario', 'programa'), name='uniq_usuario_programa'), models.CheckConstraint(condition=models.Q(models.Q(('programa__isnull', True), ('ruta__isnull', False)), models.Q(('programa__isnull', False), ('ruta__isnull', True)), _connector='OR'), name='progreso_un_curso')],
            },
        ),
    ]
