# Generated by Django 6.1 on 2026-08-30 22:51 — edited for data-preserving FK migration
import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def _unique_slug_for_migration(queryset_or_manager, base_slug):
    # accepts QuerySet or Manager
    qs = queryset_or_manager
    # if it's a Manager, filter works; if QuerySet, filter also works
    # Need to handle both: use .filter via qs
    slug = base_slug
    i = 1
    # queryset_or_manager may be Manager or QuerySet; both have filter
    while qs.filter(slug=slug).exists():
        slug = f"{base_slug}-{i}"
        i += 1
    return slug


def migrate_categorias(apps, schema_editor):
    # Use raw SQL to read old varchar values before column is dropped
    # apps.get_model for Categoria and Ruta reflects NEW state, so for old data we query DB directly
    db_alias = schema_editor.connection.alias
    # Ensure Categoria table exists
    Categoria = apps.get_model('main', 'Categoria')
    # Create default categorias (from old choices) if not exist
    defaults = [
        ('Eje transversal', 0),
        ('Agroproductivo', 1),
        ('Tecnico industrial', 2),
        ('Creativo digital', 3),
    ]
    for nombre, orden in defaults:
        if not Categoria.objects.using(db_alias).filter(nombre=nombre).exists():
            base = slugify(nombre)[:90] or 'categoria'
            # pass manager queryset
            slug = _unique_slug_for_migration(Categoria.objects.using(db_alias), base)
            Categoria.objects.using(db_alias).create(nombre=nombre, slug=slug, orden=orden, activa=True)

    # Migrate existing Ruta varchar categoria -> FK
    # At this point table still has old 'categoria' varchar column + new 'categoria_tmp_id' FK column
    # We added categoria_tmp via AddField, so we can read old values with raw SQL
    with schema_editor.connection.cursor() as cursor:
        # fetch old categoria strings
        try:
            cursor.execute('SELECT id, categoria FROM main_ruta;')
            rows = cursor.fetchall()
        except Exception:
            rows = []
        for ruta_id, old_cat in rows:
            if not old_cat:
                continue
            old_cat = old_cat.strip()
            # get or create Categoria for old value
            cat = Categoria.objects.using(db_alias).filter(nombre__iexact=old_cat).first()
            if not cat:
                base = slugify(old_cat)[:90] or 'categoria'
                slug = _unique_slug_for_migration(Categoria.objects.using(db_alias), base)
                # try unique nombre; if collision due to case, use old_cat
                cat = Categoria.objects.using(db_alias).create(nombre=old_cat, slug=slug, orden=99, activa=True)
            # update FK tmp column
            cursor.execute('UPDATE main_ruta SET categoria_tmp_id = %s WHERE id = %s', [cat.id, ruta_id])


def reverse_migrate_categorias(apps, schema_editor):
    # reverse: copy FK nombre back to varchar column (which will be recreated on reverse)
    # No-op for simple reverse; Django will recreate old schema
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_progreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True, verbose_name='Slug')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activa', models.BooleanField(default=True, help_text='Si está desactivada no aparece en filtros', verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        # Add temporary FK; old varchar 'categoria' still exists at this point
        migrations.AddField(
            model_name='ruta',
            name='categoria_tmp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas_tmp', to='main.categoria'),
        ),
        migrations.RunPython(migrate_categorias, reverse_migrate_categorias),
        # Now drop old varchar field
        migrations.RemoveField(
            model_name='ruta',
            name='categoria',
        ),
        migrations.RenameField(
            model_name='ruta',
            old_name='categoria_tmp',
            new_name='categoria',
        ),
        migrations.AlterField(
            model_name='ruta',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas', to='main.categoria', verbose_name='Categoría'),
        ),
        migrations.DeleteModel(
            name='Card',
        ),
    ]
